name: Unit Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install torch
        run: pip install torch torchvision torchaudio
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Download dataset
        run: wget -O ego_graphs.zip https://figshare.com/ndownloader/articles/20310240/versions/1
      - name: Unzip dataset
        run: unzip ego_graphs.zip -D data
      - name: Unzip each subfolder
        working-directory: ./data
        run: for k in *.zip; do unzip $k; done
      - name: Run tests
        run: bash run_tests.sh
